#ifndef THEME_H
#define THEME_H

extern const char * css_theme =
"/* Default button styling */"
"button {"
"  min-height: 32px;"
"  padding: 8px 16px;"
"  border: 1px solid #ccc;"
"  border-radius: 4px;"
"  background: linear-gradient(to bottom, #fff, #f0f0f0);"
"  color: #333;"
"  font-size: 13px;"
"  font-weight: normal;"
"}"
"button:hover {"
"  background: linear-gradient(to bottom, #f0f0f0, #e0e0e0);"
"  border-color: #999;"
"}"
"button:active {"
"  background: #e0e0e0;"
"  box-shadow: inset 0 1px 3px rgba(0,0,0,0.2);"
"}"
"button:disabled {"
"  background: #f5f5f5;"
"  color: #999;"
"  border-color: #ddd;"
"  opacity: 0.6;"
"}"
"/* Primary button */"
".btn-primary {"
"  background: linear-gradient(to bottom, #007acc, #005a9e);"
"  border-color: #007acc;"
"  color: white;"
"  font-weight: bold;"
"}"
".btn-primary:hover {"
"  background: linear-gradient(to bottom, #005a9e, #004578);"
"}"
"/* Success button */"
".btn-success {"
"  background: linear-gradient(to bottom, #4CAF50, #45a049);"
"  border-color: #4CAF50;"
"  color: white;"
"}"
".btn-success:hover {"
"  background: linear-gradient(to bottom, #45a049, #3d8b40);"
"}"
"/* Danger button */"
".btn-danger {"
"  background: linear-gradient(to bottom, #f44336, #da190b);"
"  border-color: #f44336;"
"  color: white;"
"}"
".btn-danger:hover {"
"  background: linear-gradient(to bottom, #da190b, #c62828);"
"}"
"/* Rounded button */"
".btn-rounded {"
"  border-radius: 20px;"
"  padding: 10px 24px;"
"}"
"/* Large button */"
".btn-large {"
"  padding: 12px 32px;"
"  font-size: 16px;"
"  min-height: 48px;"
"}"
;
#endif